#E:\learn-code\backend-pos\docker-compose.yml


version: '3.8'

services:
  redis:
    image: redis:7.2-alpine
    container_name: redis-container
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 30s
      retries: 3

  node_app:
    build: .
    container_name: backend-pos-container
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - REDIS_URL=redis://redis:6379
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - ./:/app
      - /app/node_modules
    restart: unless-stopped

volumes:
  redis_data: