version: '3.8'

services:
  
  
  redis:
    image: redis:7.2-alpine
    container_name: redis-container
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 30s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M

  node_app:
    build: .
    container_name: backend-pos-container
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: development
      REDIS_URL: redis://redis:6379
      MONGODB_URI: mongodb://host.docker.internal:27017/BackendPoS
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - ./:/app
      - /app/node_modules
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: '1.5'
          memory: 1G

volumes:
  redis_data: